Repository lisa-analyzer/lisa, pull requests merged in 2020-12, with the labels that each got.

#15 Pipeline changes
  .github/workflows/release.yml
  lisa/build.gradle
  lisa/doc-extra.gradle
  lisa/java.gradle
  lisa/publishing.gradle
Labels: infrastructure, refactoring

#17 Graph data structure with generic fixpoint
  lisa/src/main/java/it/unive/lisa/LiSA.java
  lisa/src/main/java/it/unive/lisa/analysis/ExpressionStore.java
  lisa/src/main/java/it/unive/lisa/analysis/StatementStore.java
  lisa/src/main/java/it/unive/lisa/callgraph/CallGraph.java
  lisa/src/main/java/it/unive/lisa/callgraph/impl/intraproc/IntraproceduralCallGraph.java
  lisa/src/main/java/it/unive/lisa/cfg/CFG.java
  lisa/src/main/java/it/unive/lisa/cfg/edge/Edge.java
  lisa/src/main/java/it/unive/lisa/cfg/edge/FalseEdge.java
  lisa/src/main/java/it/unive/lisa/cfg/edge/SequentialEdge.java
  lisa/src/main/java/it/unive/lisa/cfg/edge/TrueEdge.java
  lisa/src/main/java/it/unive/lisa/cfg/statement/Assignment.java
  lisa/src/main/java/it/unive/lisa/cfg/statement/Call.java
  lisa/src/main/java/it/unive/lisa/cfg/statement/Expression.java
  lisa/src/main/java/it/unive/lisa/cfg/statement/Literal.java
  lisa/src/main/java/it/unive/lisa/cfg/statement/NoOp.java
  lisa/src/main/java/it/unive/lisa/cfg/statement/NullLiteral.java
  lisa/src/main/java/it/unive/lisa/cfg/statement/Ret.java
  lisa/src/main/java/it/unive/lisa/cfg/statement/Return.java
  lisa/src/main/java/it/unive/lisa/cfg/statement/Statement.java
  lisa/src/main/java/it/unive/lisa/cfg/statement/Throw.java
  lisa/src/main/java/it/unive/lisa/cfg/statement/Variable.java
  lisa/src/main/java/it/unive/lisa/outputs/DotCFG.java
  lisa/src/main/java/it/unive/lisa/outputs/DotGraph.java
  lisa/src/main/java/it/unive/lisa/outputs/compare/JsonReportComparer.java
  lisa/src/main/java/it/unive/lisa/util/datastructures/graph/AdjacencyMatrix.java
  lisa/src/main/java/it/unive/lisa/util/datastructures/graph/Edge.java
  lisa/src/main/java/it/unive/lisa/util/datastructures/graph/FixpointException.java
  lisa/src/main/java/it/unive/lisa/util/datastructures/graph/FixpointGraph.java
  lisa/src/main/java/it/unive/lisa/util/datastructures/graph/Graph.java
  lisa/src/main/java/it/unive/lisa/util/datastructures/graph/Node.java
  lisa/src/main/java/it/unive/lisa/util/datastructures/graph/SemanticEdge.java
  lisa/src/test/java/it/unive/lisa/test/imp/IMPFrontend.java
  lisa/src/test/java/it/unive/lisa/test/imp/expressions/IMPAssert.java
Labels: refactoring

#19 Implementation of basic numerical abstract domains
  lisa/imp-testcases/numeric/int-const/analysis___untyped_constants().dot
  lisa/imp-testcases/numeric/int-const/analysis___untyped_div(untyped_i,_untyped_j).dot
  lisa/imp-testcases/numeric/int-const/analysis___untyped_gcd(untyped_a,_untyped_b).dot
  lisa/imp-testcases/numeric/int-const/analysis___untyped_intv_dec().dot
  lisa/imp-testcases/numeric/int-const/analysis___untyped_sign_parity_example().dot
  lisa/imp-testcases/numeric/int-const/analysis___untyped_ub_example(untyped_y,_untyped_z).dot
  lisa/imp-testcases/numeric/int-const/report.json
  lisa/imp-testcases/numeric/interval/analysis___untyped_constants().dot
  lisa/imp-testcases/numeric/interval/analysis___untyped_div(untyped_i,_untyped_j).dot
  lisa/imp-testcases/numeric/interval/analysis___untyped_gcd(untyped_a,_untyped_b).dot
  lisa/imp-testcases/numeric/interval/analysis___untyped_intv_dec().dot
  lisa/imp-testcases/numeric/interval/analysis___untyped_sign_parity_example().dot
  lisa/imp-testcases/numeric/interval/analysis___untyped_ub_example(untyped_y,_untyped_z).dot
  lisa/imp-testcases/numeric/interval/report.json
  lisa/imp-testcases/numeric/parity/analysis___untyped_constants().dot
  lisa/imp-testcases/numeric/parity/analysis___untyped_div(untyped_i,_untyped_j).dot
  lisa/imp-testcases/numeric/parity/analysis___untyped_gcd(untyped_a,_untyped_b).dot
  lisa/imp-testcases/numeric/parity/analysis___untyped_intv_dec().dot
  lisa/imp-testcases/numeric/parity/analysis___untyped_sign_parity_example().dot
  lisa/imp-testcases/numeric/parity/analysis___untyped_ub_example(untyped_y,_untyped_z).dot
  lisa/imp-testcases/numeric/parity/report.json
  lisa/imp-testcases/numeric/program.imp
  lisa/imp-testcases/numeric/sign/analysis___untyped_constants().dot
  lisa/imp-testcases/numeric/sign/analysis___untyped_div(untyped_i,_untyped_j).dot
  lisa/imp-testcases/numeric/sign/analysis___untyped_gcd(untyped_a,_untyped_b).dot
  lisa/imp-testcases/numeric/sign/analysis___untyped_intv_dec().dot
  lisa/imp-testcases/numeric/sign/analysis___untyped_sign_parity_example().dot
  lisa/imp-testcases/numeric/sign/analysis___untyped_ub_example(untyped_y,_untyped_z).dot
  lisa/imp-testcases/numeric/sign/report.json
  lisa/src/main/java/it/unive/lisa/analysis/CartesianProduct.java
  lisa/src/main/java/it/unive/lisa/analysis/FunctionalLattice.java
  lisa/src/main/java/it/unive/lisa/analysis/ValueCartesianProduct.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/numeric/IntegerConstantPropagation.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/numeric/Interval.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/numeric/Parity.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/numeric/Sign.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/BaseNonRelationalValueDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/NonRelationalDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/NonRelationalHeapDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/NonRelationalValueDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/ValueEnvironment.java
  lisa/src/test/java/it/unive/lisa/test/imp/expressions/IMPFieldAccess.java
  lisa/src/test/java/it/unive/lisa/test/numeric/NumericAnalysesTest.java
Labels: enhancement, work in progress
