Repository lisa-analyzer/lisa, pull requests merged in 2021-04, with the labels that each got.

#56 Reasoning about type cast and type conversion expressions for base non relational value domain
  lisa/src/main/java/it/unive/lisa/analysis/impl/types/InferredTypes.java
  lisa/src/main/java/it/unive/lisa/analysis/inference/BaseInferredValue.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/value/BaseNonRelationalValueDomain.java
Labels: enhancement

#60 Semantic checks
  lisa/src/main/java/it/unive/lisa/LiSA.java
  lisa/src/main/java/it/unive/lisa/LiSAConfiguration.java
  lisa/src/main/java/it/unive/lisa/checks/Check.java
  lisa/src/main/java/it/unive/lisa/checks/ChecksExecutor.java
  lisa/src/main/java/it/unive/lisa/checks/semantic/CheckToolWithAnalysisResults.java
  lisa/src/main/java/it/unive/lisa/checks/semantic/SemanticCheck.java
  lisa/src/main/java/it/unive/lisa/checks/syntactic/CheckTool.java
  lisa/src/main/java/it/unive/lisa/checks/syntactic/SyntacticCheck.java
  lisa/src/main/java/it/unive/lisa/checks/syntactic/SyntacticChecksExecutor.java
  lisa/src/main/java/it/unive/lisa/program/cfg/CFGDescriptor.java
  lisa/src/main/java/it/unive/lisa/program/cfg/VariableTableEntry.java
  lisa/src/test/java/it/unive/lisa/checks/ChecksExecutorTest.java
Labels: enhancement

#64 Symbolic expressions collections as set lattice instances
  lisa/imp-testcases/heap/point-based-heap/field-insensitive/analysis___untyped_A.f3(A_this).dot
  lisa/imp-testcases/heap/point-based-heap/field-sensitive/analysis___untyped_A.f3(A_this).dot
  lisa/src/main/java/it/unive/lisa/analysis/AnalysisState.java
  lisa/src/main/java/it/unive/lisa/analysis/SemanticExceptionWrapper.java
  lisa/src/main/java/it/unive/lisa/analysis/SimpleAbstractState.java
  lisa/src/main/java/it/unive/lisa/analysis/heap/HeapSemanticOperation.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/heap/MonolithicHeap.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/heap/TypeBasedHeap.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/heap/pointbased/AllocationSites.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/heap/pointbased/FieldSensitivePointBasedHeap.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/heap/pointbased/PointBasedHeap.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/types/InferredTypes.java
  lisa/src/main/java/it/unive/lisa/analysis/lattices/ExpressionSet.java
  lisa/src/main/java/it/unive/lisa/analysis/lattices/InverseSetLattice.java
  lisa/src/main/java/it/unive/lisa/analysis/lattices/SetLattice.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/heap/HeapEnvironment.java
  lisa/src/main/java/it/unive/lisa/callgraph/CallGraph.java
  lisa/src/main/java/it/unive/lisa/callgraph/impl/intraproc/IntraproceduralCallGraph.java
  lisa/src/main/java/it/unive/lisa/program/cfg/edge/FalseEdge.java
  lisa/src/main/java/it/unive/lisa/program/cfg/edge/TrueEdge.java
  lisa/src/main/java/it/unive/lisa/program/cfg/statement/BinaryNativeCall.java
  lisa/src/main/java/it/unive/lisa/program/cfg/statement/CFGCall.java
  lisa/src/main/java/it/unive/lisa/program/cfg/statement/Call.java
  lisa/src/main/java/it/unive/lisa/program/cfg/statement/OpenCall.java
  lisa/src/main/java/it/unive/lisa/program/cfg/statement/TernaryNativeCall.java
  lisa/src/main/java/it/unive/lisa/program/cfg/statement/UnaryNativeCall.java
  lisa/src/main/java/it/unive/lisa/program/cfg/statement/UnresolvedCall.java
  lisa/src/main/java/it/unive/lisa/util/collections/CollectionUtilities.java
  lisa/src/main/java/it/unive/lisa/util/collections/Utils.java
  lisa/src/main/java/it/unive/lisa/util/datastructures/graph/AdjacencyMatrix.java
  lisa/src/test/java/it/unive/lisa/imp/expressions/IMPNewArray.java
  lisa/src/test/java/it/unive/lisa/imp/expressions/IMPNewObj.java
  lisa/src/test/java/it/unive/lisa/program/cfg/FixpointTest.java
  lisa/src/test/java/it/unive/lisa/program/cfg/SemanticsSanityTest.java
Labels: enhancement, refactoring

#65 Support for conditional structures
  lisa/src/main/java/it/unive/lisa/program/cfg/CFG.java
  lisa/src/main/java/it/unive/lisa/program/cfg/controlFlow/ControlFlowExtractor.java
  lisa/src/main/java/it/unive/lisa/program/cfg/controlFlow/ControlFlowStructure.java
  lisa/src/main/java/it/unive/lisa/program/cfg/controlFlow/IfThenElse.java
  lisa/src/main/java/it/unive/lisa/program/cfg/controlFlow/Loop.java
  lisa/src/main/java/it/unive/lisa/util/datastructures/graph/AdjacencyMatrix.java
  lisa/src/main/java/it/unive/lisa/util/datastructures/graph/Graph.java
  lisa/src/main/java/it/unive/lisa/util/datastructures/graph/algorithms/Dominators.java
  lisa/src/main/java/it/unive/lisa/util/workset/VisitOnceWorkingSet.java
  lisa/src/test/java/it/unive/lisa/imp/IMPCodeMemberVisitor.java
  lisa/src/test/java/it/unive/lisa/program/cfg/CFGSimplificationTest.java
  lisa/src/test/java/it/unive/lisa/program/cfg/ConditionalsExtractionTest.java
Labels: enhancement

#70 InferenceSystem equals and hashCode methods
  lisa/src/main/java/it/unive/lisa/analysis/inference/InferenceSystem.java
Labels: bug

#72 Greatest lower bound for set domains
  lisa/src/main/java/it/unive/lisa/analysis/BaseLattice.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/heap/pointbased/AllocationSites.java
  lisa/src/main/java/it/unive/lisa/analysis/lattices/InverseSetLattice.java
  lisa/src/main/java/it/unive/lisa/analysis/lattices/SetLattice.java
Labels: enhancement

#77 Equals and hashCode methods for set-based lattice implementations and FunctionalLattice
  lisa/src/main/java/it/unive/lisa/analysis/dataflow/DefiniteForwardDataflowDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/dataflow/PossibleForwardDataflowDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/heap/pointbased/AllocationSites.java
  lisa/src/main/java/it/unive/lisa/analysis/lattices/ExpressionSet.java
  lisa/src/main/java/it/unive/lisa/analysis/lattices/FunctionalLattice.java
Labels: bug

#79 Interval greatest lower bound fixes
  lisa/src/main/java/it/unive/lisa/analysis/impl/numeric/Interval.java
Labels: bug

#80 Interval multiplication fix
  lisa/src/main/java/it/unive/lisa/analysis/impl/numeric/Interval.java
Labels: bug

#85 Interval satisfies method
  lisa/imp-testcases/interval/analysis___untyped_tutorial.sat(tutorial_this,_untyped_x,_untyped_y).dot
  lisa/imp-testcases/interval/program.imp
  lisa/imp-testcases/interval/report.json
  lisa/src/main/java/it/unive/lisa/analysis/impl/numeric/Interval.java
Labels: enhancement

#88 Structured domain representation
  lisa/dependencies.gradle
  lisa/imp-testcases/reaching-definitions/analysis___untyped_reachingDefinitions.test1(reachingDefinitions_this).dot
  lisa/imp-testcases/reaching-definitions/analysis___untyped_reachingDefinitions.test2(reachingDefinitions_this).dot
  lisa/imp-testcases/reaching-definitions/analysis___untyped_reachingDefinitions.test3(reachingDefinitions_this).dot
  lisa/src/main/java/it/unive/lisa/LiSA.java
  lisa/src/main/java/it/unive/lisa/analysis/AnalysisState.java
  lisa/src/main/java/it/unive/lisa/analysis/Lattice.java
  lisa/src/main/java/it/unive/lisa/analysis/SemanticDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/SimpleAbstractState.java
  lisa/src/main/java/it/unive/lisa/analysis/combination/CartesianProduct.java
  lisa/src/main/java/it/unive/lisa/analysis/combination/ValueCartesianProduct.java
  lisa/src/main/java/it/unive/lisa/analysis/dataflow/DataflowElement.java
  lisa/src/main/java/it/unive/lisa/analysis/dataflow/DefiniteForwardDataflowDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/dataflow/PossibleForwardDataflowDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/dataflow/impl/AvailableExpressions.java
  lisa/src/main/java/it/unive/lisa/analysis/dataflow/impl/ConstantPropagation.java
  lisa/src/main/java/it/unive/lisa/analysis/dataflow/impl/ReachingDefinitions.java
  lisa/src/main/java/it/unive/lisa/analysis/heap/BaseHeapDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/heap/MonolithicHeap.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/heap/TypeBasedHeap.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/heap/pointbased/AllocationSites.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/heap/pointbased/PointBasedHeap.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/numeric/IntegerConstantPropagation.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/numeric/Interval.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/numeric/Parity.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/numeric/Sign.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/types/InferredTypes.java
  lisa/src/main/java/it/unive/lisa/analysis/inference/BaseInferredValue.java
  lisa/src/main/java/it/unive/lisa/analysis/inference/InferenceSystem.java
  lisa/src/main/java/it/unive/lisa/analysis/lattices/InverseSetLattice.java
  lisa/src/main/java/it/unive/lisa/analysis/lattices/SetLattice.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/Environment.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/NonRelationalDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/value/BaseNonRelationalValueDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/representation/DomainRepresentation.java
  lisa/src/main/java/it/unive/lisa/analysis/representation/MapRepresentation.java
  lisa/src/main/java/it/unive/lisa/analysis/representation/PairRepresentation.java
  lisa/src/main/java/it/unive/lisa/analysis/representation/SetRepresentation.java
  lisa/src/main/java/it/unive/lisa/analysis/representation/StringRepresentation.java
  lisa/src/main/java/it/unive/lisa/util/collections/IterableArray.java
Labels: enhancement

#73 Non interference
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec16(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec17(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec18ex1(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec18ex2(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec19ex1(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec19ex2(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec19ex3(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec19ex4(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec19ex5(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec5ex1(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec5ex2(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec6(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec7(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/analysis___untyped_Confidentiality.confidentiality_lec8(Confidentiality_this).dot
  lisa/imp-testcases/non-interference/confidentiality/program.imp
  lisa/imp-testcases/non-interference/confidentiality/report.json
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec16(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec17(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec18ex1(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec18ex2(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec19ex1(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec19ex2(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec19ex3(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec19ex4(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec19ex5(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec5ex1(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec5ex2(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec6(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec7(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/analysis___untyped_Integrity.integrity_lec8(Integrity_this).dot
  lisa/imp-testcases/non-interference/integrity/program.imp
  lisa/imp-testcases/non-interference/integrity/report.json
  lisa/src/main/java/it/unive/lisa/analysis/combination/CartesianProduct.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/nonInterference/NonInterference.java
  lisa/src/main/java/it/unive/lisa/analysis/impl/types/InferredTypes.java
  lisa/src/main/java/it/unive/lisa/analysis/inference/BaseInferredValue.java
  lisa/src/main/java/it/unive/lisa/analysis/inference/InferenceSystem.java
  lisa/src/main/java/it/unive/lisa/analysis/inference/InferredValue.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/Environment.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/NonRelationalDomain.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/NonRelationalElement.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/heap/HeapEnvironment.java
  lisa/src/main/java/it/unive/lisa/analysis/nonrelational/value/ValueEnvironment.java
  lisa/src/main/java/it/unive/lisa/analysis/representation/PairRepresentation.java
  lisa/src/main/java/it/unive/lisa/program/cfg/CFG.java
  lisa/src/test/java/it/unive/lisa/AnalysisTestExecutor.java
  lisa/src/test/java/it/unive/lisa/analysis/impl/types/InferredTypesTest.java
  lisa/src/test/java/it/unive/lisa/cron/nonInterference/NonInterferenceTest.java
Labels: enhancement
