Repository lisa-analyzer/lisa, pull requests merged in 2022-12, with the labels that each got.

#259 Base interfaces
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/SimpleAbstractState.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/combination/NonRelationalValueCartesianProduct.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/heap/MonolithicHeap.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/heap/TypeBasedHeap.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/heap/pointbased/PointBasedHeap.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/nonInterference/NonInterference.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/numeric/IntegerConstantPropagation.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/numeric/Interval.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/numeric/Parity.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/numeric/Sign.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/string/CharInclusion.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/string/Prefix.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/string/Suffix.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/string/fsa/FSA.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/types/InferredTypes.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/types/StaticTypes.java
  lisa/lisa-analyses/src/test/java/it/unive/lisa/analysis/nonrelational/inference/BaseInferredValueTest.java
  lisa/lisa-analyses/src/test/java/it/unive/lisa/analysis/nonrelational/value/BaseNonRelationalTypeDomainTest.java
  lisa/lisa-analyses/src/test/java/it/unive/lisa/analysis/nonrelational/value/BaseNonRelationalValueDomainTest.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/IMPAnnotationVisitor.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/AnalysisState.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/BaseLattice.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/Lattice.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/dataflow/DataflowDomain.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/heap/BaseHeapDomain.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/lattices/FunctionalLattice.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/lattices/InverseSetLattice.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/lattices/SetLattice.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/inference/BaseInferredValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/inference/InferredValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/value/BaseNonRelationalTypeDomain.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/value/BaseNonRelationalValueDomain.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/Annotation.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/AnnotationMember.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/Annotations.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/AnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/ArrayAnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/BoolAnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/ByteAnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/CharAnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/CompilationUnitAnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/DoubleAnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/EnumAnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/FloatAnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/IntAnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/LongAnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/ShortAnnotationValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/annotations/values/StringAnnotationValue.java
  lisa/lisa-sdk/src/test/java/it/unive/lisa/TestDomain.java
Labels: 🎆 type:feature, 🏨 scope:infrastructure

#261 Updating build badge
  README.md
Labels: 🛠 type:refactoring, 🏨 scope:infrastructure

#250 Support for static allocation in LiSA point-based heap analyses
  lisa/lisa-analyses/imp-testcases/heap/point-based-heap/field-insensitive/program.imp
  lisa/lisa-analyses/imp-testcases/heap/point-based-heap/field-insensitive/report.json
  lisa/lisa-analyses/imp-testcases/heap/point-based-heap/field-insensitive/untyped_A.f1(A__this).json
  lisa/lisa-analyses/imp-testcases/heap/point-based-heap/field-insensitive/untyped_A.f4(A__this).json
  lisa/lisa-analyses/imp-testcases/heap/point-based-heap/field-insensitive/untyped_A.f8(A__this).json
  lisa/lisa-analyses/imp-testcases/heap/point-based-heap/field-insensitive/untyped_A.f9(A__this).json
  lisa/lisa-analyses/imp-testcases/heap/point-based-heap/field-sensitive/program.imp
  lisa/lisa-analyses/imp-testcases/heap/point-based-heap/field-sensitive/report.json
  lisa/lisa-analyses/imp-testcases/heap/point-based-heap/field-sensitive/untyped_A.f8(A__this).json
  lisa/lisa-analyses/imp-testcases/heap/point-based-heap/field-sensitive/untyped_A.f9(A__this).json
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/heap/MonolithicHeap.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/heap/TypeBasedHeap.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/heap/pointbased/FieldSensitivePointBasedHeap.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/heap/pointbased/HeapAllocationSite.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/heap/pointbased/PointBasedHeap.java
  lisa/lisa-analyses/src/main/java/it/unive/lisa/analysis/heap/pointbased/StackAllocationSite.java
  lisa/lisa-analyses/src/test/java/it/unive/lisa/analysis/heap/pointbased/PointBasedHeapTest.java
  lisa/lisa-imp/example.imp
  lisa/lisa-imp/src/main/antlr/IMPLexer.g4
  lisa/lisa-imp/src/main/antlr/IMPParser.g4
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/IMPCodeMemberVisitor.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPNewArray.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPNewObj.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/inference/BaseInferredValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/value/BaseNonRelationalTypeDomain.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/value/BaseNonRelationalValueDomain.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/symbolic/ExpressionVisitor.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/symbolic/heap/HeapAllocation.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/symbolic/heap/MemoryAllocation.java
Labels: 🎆 type:feature, 🔍 scope:analysis
