Repository lisa-analyzer/lisa, pull requests merged in 2022-01, with the labels that each got.

#150 Updating to a more recent version of log4j
  lisa/lisa-core/src/test/java/it/unive/lisa/program/cfg/SemanticsSanityTest.java
  lisa/lisa-sdk/build.gradle
Labels: bug, priority-p1

#155 General bugfixing
  lisa/lisa-core/src/main/java/it/unive/lisa/analysis/combination/CartesianProduct.java
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/CallGraphBasedAnalysis.java
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/ContextBasedAnalysis.java
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/ContextInsensitiveToken.java
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/ModularWorstCaseAnalysis.java
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/RecursionFreeToken.java
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/SingleScopeToken.java
  lisa/lisa-core/src/test/java/it/unive/lisa/EqualityContractVerificationTest.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/BaseLattice.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/CFGWithAnalysisResults.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/dataflow/DataflowDomain.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/heap/BaseHeapDomain.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/lattices/FunctionalLattice.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/lattices/InverseSetLattice.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/lattices/SetLattice.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/Environment.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/heap/HeapEnvironment.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/inference/BaseInferredValue.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/value/BaseNonRelationalValueDomain.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/nonrelational/value/ValueEnvironment.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/checks/warnings/CFGDescriptorWarning.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/checks/warnings/ExpressionWarning.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/checks/warnings/GlobalWarning.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/checks/warnings/StatementWarning.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/checks/warnings/UnitWarning.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/checks/warnings/WarningWithLocation.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/interprocedural/callgraph/BaseCallGraph.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/outputs/DotCFG.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/CompilationUnit.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/Program.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/SyntheticLocation.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/controlFlow/ControlFlowStructure.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/Expression.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/Call.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/HybridCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/symbolic/heap/HeapExpression.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/NullType.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/TypeTokenType.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/Untyped.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/VoidType.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/BoolType.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/Float32.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/Float64.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/Int16.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/Int32.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/Int64.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/Int8.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/StringType.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/UInt16.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/UInt32.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/UInt64.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/type/common/UInt8.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/util/datastructures/graph/Graph.java
  lisa/lisa-sdk/src/test/java/it/unive/lisa/interprocedural/callgraph/CallRegisteringTest.java
Labels: bug, enhancement

#156 Open calls
  lisa/lisa-core/imp-testcases/interprocedural/CHA/analysis___untyped_tests.subtyping(tests_this).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTA/analysis___untyped_tests.subtyping(tests_this).dot
  lisa/lisa-core/src/main/java/it/unive/lisa/LiSAConfiguration.java
  lisa/lisa-core/src/main/java/it/unive/lisa/LiSARunner.java
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/CallGraphBasedAnalysis.java
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/ContextBasedAnalysis.java
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/ModularWorstCaseAnalysis.java
  lisa/lisa-core/src/test/java/it/unive/lisa/program/cfg/CFGFixpointTest.java
  lisa/lisa-core/src/test/java/it/unive/lisa/program/cfg/SemanticsSanityTest.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/interprocedural/InterproceduralAnalysis.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/interprocedural/OpenCallPolicy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/interprocedural/ReturnTopPolicy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/interprocedural/WorstCasePolicy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/CFGCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/CallWithResult.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/OpenCall.java
Labels: enhancement, refactoring

#160 Fixed CallGraphBasedAnalysis's init method
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/CallGraphBasedAnalysis.java
Labels: bug

#166 Snapshot and actions
  .github/release-drafter-config.yml
  .github/workflows/broken-links.yml
  .github/workflows/closed-issues.yml
  .github/workflows/created-prs.yml
  .github/workflows/cron-runner.yml
  .github/workflows/cron-scheduler.yml
  .github/workflows/docs-links-checker.yml
  .github/workflows/gradle-all.yml
  .github/workflows/gradle-master.yml
  .github/workflows/pr.yml
  .github/workflows/ready-prs.yml
  .github/workflows/release-drafter.yml
  .github/workflows/resolved-issues.yml
  lisa/build.gradle
  lisa/gradle.properties
Labels: type:feature, scope:build

#167 Restoring short-circuit capabilities
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPAddOrConcat.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPArrayAccess.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPNewArray.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPNewObj.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/Assignment.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/BinaryExpression.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/NaryExpression.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/TernaryExpression.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/UnaryExpression.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/CallWithResult.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/HybridCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/UnresolvedCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/comparison/Equal.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/comparison/GreaterOrEqual.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/comparison/GreaterThan.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/comparison/LessOrEqual.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/comparison/LessThan.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/comparison/NotEqual.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/logic/And.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/logic/Not.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/logic/Or.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Addition.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Division.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Multiplication.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Negation.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Remainder.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Subtraction.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/string/Concat.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/string/Contains.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/string/EndsWith.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/string/Equals.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/string/IndexOf.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/string/Length.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/string/Replace.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/string/StartsWith.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/string/Substring.java
Labels: type:feature, scope:analysis

#168 Call resolution v2
  lisa/lisa-core/imp-testcases/interprocedural/CHA/analysis___untyped_tests.subtyping(tests_this).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTA/analysis___untyped_tests.subtyping(tests_this).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive1/analysis___-1134695237_untyped_A.getPositive(A_this,_untyped_i).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive1/analysis___-1135618727_untyped_A.getPositive(A_this,_untyped_i).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive1/analysis___untyped_tests.main(tests_this).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive2/analysis___-1425327712_untyped_tests.helper(tests_this,_untyped_i,_untyped_dispatcher).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive2/analysis___untyped_tests.main(tests_this).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive3/analysis___-1719653279_untyped_tests.helper(tests_this,_untyped_i,_untyped_dispatcher).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive3/analysis___-1721500476_untyped_tests.helper(tests_this,_untyped_i,_untyped_dispatcher).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive3/analysis___untyped_tests.main(tests_this).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive4/analysis___-834160479_untyped_tests.helper(tests_this,_untyped_i,_untyped_dispatcher).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive4/analysis___-891423586_untyped_tests.helper(tests_this,_untyped_i,_untyped_dispatcher).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive4/analysis___untyped_tests.main(tests_this).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive5/analysis___-2041686398_untyped_A.build(A_this,_untyped_a,_untyped_b,_untyped_c).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive5/analysis___-2042609950_untyped_A.build(A_this,_untyped_a,_untyped_b,_untyped_c).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive5/analysis___untyped_A.main(A_this).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive6/analysis___1957107173_untyped_A.build(A_this,_untyped_a).dot
  lisa/lisa-core/imp-testcases/interprocedural/RTAContextSensitive6/analysis___untyped_A.main(A_this).dot
  lisa/lisa-core/imp-testcases/non-interference/interproc/analysis___-2057990561_untyped_Integrity.confidentiality_lec6_declassified(Integrity_this).dot
  lisa/lisa-core/imp-testcases/non-interference/interproc/analysis___-2086616829_untyped_Integrity.confidentiality_lec5ex1_declassified(Integrity_this).dot
  lisa/lisa-core/imp-testcases/non-interference/interproc/analysis___untyped_Integrity.main(Integrity_this).dot
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/CallGraphBasedAnalysis.java
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/ContextBasedAnalysis.java
  lisa/lisa-core/src/main/java/it/unive/lisa/interprocedural/ModularWorstCaseAnalysis.java
  lisa/lisa-core/src/test/java/it/unive/lisa/EqualityContractVerificationTest.java
  lisa/lisa-core/src/test/java/it/unive/lisa/program/cfg/SemanticsSanityTest.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/IMPCodeMemberVisitor.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/IMPFrontend.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPNewObj.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/lattices/ExpressionSet.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/interprocedural/InterproceduralAnalysis.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/interprocedural/callgraph/BaseCallGraph.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/CompilationUnit.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/CFGDescriptor.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/Parameter.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/NaryExpression.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/Statement.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/CFGCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/Call.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/CallWithResult.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/HybridCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/NamedParameterExpression.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/OpenCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/UnresolvedCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/assignment/OrderPreservingAssigningStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/assignment/ParameterAssigningStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/assignment/PythonLikeAssigningStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/resolution/FirstRuntimeThenStaticStaticResolution.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/resolution/FixedOrderMatchingStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/resolution/JavaLikeMatchingStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/resolution/ParameterMatchingStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/resolution/PythonLikeMatchingStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/resolution/RuntimeTypesMatchingStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/resolution/StaticTypesMatchingStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/traversal/HierarcyTraversalStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/traversal/SingleInheritanceTraversalStrategy.java
  lisa/lisa-sdk/src/test/java/it/unive/lisa/interprocedural/callgraph/CallRegisteringTest.java
Labels: type:feature, scope:interproc, scope:program-structure

#172 CFG validation, AnalysisState initialization, PythonLikeMatchingStrategy and HybridCall fixes
  lisa/lisa-sdk/src/main/java/it/unive/lisa/analysis/CFGWithAnalysisResults.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/CFG.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/edge/FalseEdge.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/edge/TrueEdge.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/HybridCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/resolution/PythonLikeMatchingStrategy.java
  lisa/lisa-sdk/src/test/java/it/unive/lisa/program/cfg/CFGSimplificationTest.java
Labels: type:bug, scope:analysis, scope:program-structure

#176 Python-like logic fix
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/assignment/PythonLikeAssigningStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/resolution/PythonLikeMatchingStrategy.java
Labels: type:bug, scope:interproc
