Repository lisa-analyzer/lisa, pull requests merged in 2023-12, with the labels that each got.

#295 Fixed typos in CodeMemberDescriptor javadoc strings.
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/CodeMemberDescriptor.java
Labels: 🐛 type:bug, 📑 scope:docs, ❕ priority:p4

#299 Restoring compareTo()'s
  lisa/lisa-analyses/src/test/java/it/unive/lisa/program/cfg/SemanticsSanityTest.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/constructs/ArrayLength.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPAddOrConcat.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPArrayAccess.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPAssert.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPNewArray.java
  lisa/lisa-imp/src/main/java/it/unive/lisa/imp/expressions/IMPNewObj.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/comparison/Equal.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/comparison/GreaterOrEqual.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/comparison/GreaterThan.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/comparison/LessOrEqual.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/comparison/LessThan.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/comparison/NotEqual.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/global/AccessGlobal.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/global/AccessInstanceGlobal.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/logic/And.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/logic/Not.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/logic/Or.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Addition.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Division.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Modulo.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Multiplication.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Negation.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Remainder.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/numeric/Subtraction.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/string/Concat.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/string/Contains.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/string/EndsWith.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/string/Equals.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/string/IndexOf.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/string/Length.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/string/Replace.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/string/StartsWith.java
  lisa/lisa-program/src/main/java/it/unive/lisa/program/cfg/statement/string/Substring.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/Assignment.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/DefaultParamInitialization.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/NaryExpression.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/NaryStatement.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/NoOp.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/Ret.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/Return.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/Statement.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/Throw.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/VariableRef.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/CFGCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/Call.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/MultiCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/NamedParameterExpression.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/NativeCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/OpenCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/TruncatedParamsCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/call/UnresolvedCall.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/cfg/statement/literal/Literal.java
Labels: 🎆 type:feature, 🏛 scope:program-structure, 🏨 scope:infrastructure

#303 Unconditionally dump support files
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/js/cytoscape-3.21.1.min.js
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/js/cytoscape-graphml-1.0.6-hier.js
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/js/jquery-3.0.0.min.js
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/report.json
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_A.A(A__this)_cfg.html
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_A.A(A__this)_cfg.json
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_A.getOne(A__this)_cfg.html
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_A.getOne(A__this)_cfg.json
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_A.getPositive(A__this,_untyped_i)_cfg.html
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_A.getPositive(A__this,_untyped_i)_cfg.json
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_A.identity(A__this,_untyped_i)_cfg.html
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_A.identity(A__this,_untyped_i)_cfg.json
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_tests.helper(tests__this,_untyped_i,_untyped_dispatcher)_cfg.html
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_tests.helper(tests__this,_untyped_i,_untyped_dispatcher)_cfg.json
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_tests.main(tests__this)_cfg.html
  lisa/lisa-analyses/imp-testcases/visualization/html-inputs/untyped_tests.main(tests__this)_cfg.json
  lisa/lisa-analyses/src/test/java/it/unive/lisa/cron/VisualizationTest.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/LiSA.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/LiSARunner.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/program/language/parameterassignment/PythonLikeAssigningStrategy.java
  lisa/lisa-sdk/src/main/java/it/unive/lisa/util/file/FileManager.java
Labels: 🐛 type:bug, 🏗 resolution:wip, 🏨 scope:infrastructure
